<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<script type="text/javascript">
		// 1.Generator函数的基本概念

		/*
		 Generator函数相当于一个状态机，通过使用yield表达式来定义不同的状态，返回一个包含Generator状态的遍历器对象。
		 通过调用遍历器对象的next()方法让指针指向下一个状态。也就是说每次调用next()方法，内部指针就从函数头部
		 或上一次停下来的地方开始执行，直到遇到下一个yield表达式（或return语句）为止.
		*/

		// Generator函数有2个特征，1是function与函数名之间有个星号(*)，2是函数体内部使用yield表达式

		function *helloGenerator(){
			yield 'hello';
			yield 'Generator';
			return 'hello Generator';
		}	

		var h = helloGenerator();

		h.next(); // {value: "hello", done: false}
		h.next(); // {value: "Generator", done: false}
		h.next(); // {value: "hello Generator", done: true} 
		//每次调用next()方法会返回一个对象，它的value属性就是当前yield表达式的值，
		//done属性的值false或true，表示遍历还没有结束或已经结束

		/*
			调用 Generator 函数，返回一个遍历器对象，代表 Generator 函数的内部指针。
			以后，每次调用遍历器对象的next方法，就会返回一个有着value和done两个属性的对象。
			value属性表示当前的内部状态的值，是yield表达式后面那个表达式的值；done属性是一个布尔值，表示是否遍历结束。
		*/



		// yield表达式 

		//  Generator 函数返回的遍历器对象，只有调用next方法才会遍历下一个内部状态，所以其实提供了一种可以暂停执行的函数。yield表达式就是暂停标志。

		/** 遍历器对象的next方法的运行逻辑：
				遇到yield表达式就暂停执行后面的操作，将yield表达式的值作为返回对象的value的值，
				下一次在调用next方法时，再继续往下执行，知道遇到下一个yield表达式。
				如果没有遇到新的yield表达式，就一直运行到函数结束或者遇到return语句为止，并将return后面的值作为返回对象的
				value值。
				如果该函数没有return语句，则返回的对象的value属性值为undefined。
		*/

		//需要注意的是，yield表达式后面的表达式，只有当调用next方法、内部指针指向该语句时才会执行


		// 与return不同的是 一个函数只能有一个return 而 Generator可以使用yield表达式返回一系列的值，但是每次遇到yield，
		// 会暂停执行当前函数，下一次调用时再从该位置继续向后执行。

		// 2.next()方法的参数
 			// yield表达式本身没有返回值，或者说返回undefined.可以通过next()方法带入一个参数，用来被当作上一个yield表达式的返回值。
		function* f() {
		  for(var i = 0; true; i++) {
		    var reset = yield i;
		    if(reset) { i = -1; }
		  }
		}

		var g = f();

		g.next() // { value: 0, done: false }
		g.next() // { value: 1, done: false }
		g.next(true) // { value: 0, done: false }

		/*
			上面代码先定义了一个可以无限运行的 Generator 函数f，如果next方法没有参数，每次运行到yield表达式，变量reset的值总
			是undefined。当next方法带一个参数true时，变量reset就被重置为这个参数（即true），因此i会等于-1，下一轮循环就会从-1开始递增。
		*/
		function *foo(x) {
			var y = 2 * (yield (x + 1));
			var z = yield (y / 3);
			return (x + y + z);
		}

		var a = foo(5);
		console.log(a.next()); // {value: 6, done: false}
		console.log(a.next())  // {value: NaN, done: false} 
		// 第二次调用next方法时没有传入参数，导致Y的值为2*undefined,即NaN,除3了以后还是NaN
		console.log(a.next())  // {value: NaN, done: true}
		// 第三次调用next方法时还是没有带参数，即z的undefined,返回的值是5+NaN+undefined，即NaN

		var b = foo(5);

		console.log(b.next()) // {value: 6, done: false}
		console.log(b.next(12)) // { value:8, done:false }
		// 第二次调用时，传入了12作为上一个yield的返回值，y的值为2*12=24，返回的是y/3的值也就是8
		console.log(b.next(13)) // { value:42, done:true }
		// 第三次调用将上一个yield的值，也是就是z的值设为13，而x为5，y为24，z为13，所以是42.


		// 由于next方法的参数为上一个yield表达式的值，所以第一次调用next方法传入参数是无效的，会被直接忽略，只有第二次才有效。
		/*
			这个功能有很重要的语法意义。Generator 函数从暂停状态到恢复运行，它的上下文状态（context）是不变的。
			通过next方法的参数，就有办法在 Generator 函数开始运行之后，继续向函数体内部注入值。
			也就是说，可以在 Generator 函数运行的不同阶段，从外部向内部注入不同的值，从而调整函数行为。
		*/

		//3 for...of 

		// for...of循环可以自动遍历Generator函数生成的Iterator对象，这样可以不调用next方法

		function *foo() {
			yield 1;
			yield 2;
			yield 3;
			yield 4;
			yield 5;
		}

		for (let v of foo()) {
			console.log(v)
		}

		// 1 2 3 4 5

		function *fibonacci() {
			let [prve,curr] = [0,1] 
			for(;;) {
				[prve,curr] = [curr,prve+curr]
				yield curr;
			}
		}
		for (let n of fibonacci()) {
		  if (n > 1000) break;
		  console.log(n);
		}

		// 4 Generator.prototype.throw()

		//Generator 返回的遍历器对象，都有一个throw()方法，可以在函数体外抛出错误，
		// 然后再Generator函数体内捕获。

		//throw()方法接受一个参数，该参数会被catch语句接收。


		var g = function *() {
			try{
				yield;
			}catch(e){
				console.log("内部捕获",e)
			}
		}

		var I = g();

		try{
			I.next();
			I.throw("a");
			I.throw("b");
		}catch (e) {
			console.log('外部捕获', e);
		}
		// 内部捕获 a
		// 外部捕获 b

		/*
		 上面的代码中 遍历器对象i连续抛出了俩个错误，第一个被Generator函数的catch语句捕获，
		 第二次由于已经被执行过了，不会再捕捉错误所以就被抛出从而被函数体外的catch语句捕获。
		*/

		/*
		 如果Generator函数体内没有部署try...catch代码，那么throw方法抛出的错误将被外部的
		 try...catch代码捕获。
		*/

		// throw捕获到错误了以后，会附带执行下一条yield表达式。

		var gen = function *gener(){
			try {
				yield console.log("a");
			}catch (e) {

			};
			yield console.log('b');
			yield console.log('c');
		}

		var G = gen();

		G.next() // a
		G.throw() // b
		G.next()  // c

		/*
		 一旦 Generator 执行过程中抛出错误，且没有被内部捕获，就不会再执行下去了。如果此后还调用next方
		 法，将返回一个value属性等于undefined、done属性等于true的对象，即 JavaScript 引擎认为这个 
		 Generator 已经运行结束了。	
		*/

		// Generator.prototype.return();

		// Generator 函数返回的遍历器对象，还有一个return方法，可以返回给定的值，并且终结遍历 Generator 函数

		function *gen2() {
			yield 1;
			yield 2;
			yield 3;
		}
		var g = gen2();

		g.next() //{value: 1, done: false};
		g.return("foo") //{value: "foo", done: true};
		g.next() //{value: undefined, done: true};

		// 上面的代码中 遍历器对象g调用了return方法之后 返回对象的value值就变成了foo，done变成了ture,
		// 终止了Generator的遍历，在调动next方法done的值都为ture.
		// 如果return方法调用时，不提供参数，则返回值的value属性为undefined。

		// 6.next()、throw()、return()的共同点。

		// 本质上都是让Generator函数回复执行，并且使用不同的语句替换yield语句

		// next()是将yield 表达式替换成一个值。
		var gen3 = function *(x,y) {
			let result = yield x + y;
			return result; 
		}

		var g2 = gen3(1,2);
		g2.next(); //{value: 3, done: false}  
		g2.next(1) //{value: 1, done: true} 实际上是将 let result = yield x +y 替换成 let result = 1；

		//throw()是将yield表达式替换成一个throw语句。

		// g2.throw(new Error("出错了")); //Uncaught Error: 出错了
		// 相当于将 let result = yield x + y
		// 替换成 let result = throw(new Error('出错了'));

		//return()是将yield表达式替换成一个return语句。
		g2.return(2); // Object {value: 2, done: true}
		// 相当于将 let result = yield x + y
		// 替换成 let result = return 2;

		// 7.yield* 表达式
			//通常在一个Generator函数中调用另一个Generator函数是没有效果的。
		function* foo2() {
		  yield 'a';
		  yield 'b';
		}

		function* bar2() {
		  yield 'x';
		  foo2();
		  yield 'y';
		}

		for (let v of bar2()){
		  console.log(v);
		}
		// "x"
		// "y"
		 // 所以要通过调用yield*表达式来在一个Generator函数里执行另外一个Genterator函数。
		function* bar3() {                 // funciton *bar3(){
			yield 'x';						  	 // yield 'x
			yield* foo();    // 等同于           yield 'a';
			yield 'y';                          // yield 'b';  
												// yield 'y' };	
		}

		for (let v of bar3()){
		  console.log(v);
		}

		function *inner(){
			yield 'hello!'
		}

		function *outer1(){
			yield 'open';
			yield inner();
			yield 'close';
		}
		var g6 = outer1()
		g6.next().value // "open"
		g6.next().value// 返回一个遍历器对象
		g6.next().value // "close"

		function *outer2(){
			yield 'open';
			yield* inner();
			yield 'close';
		}

		var g7 = outer2();
		console.log(g7.next().value); // open
		console.log(g7.next().value); // hello!
		console.log(g7.next().value); // close 

		//上面代码中outer1没有使用yield*表达式，所以返回了一个遍历器对象，而outer2使用了yield表达式，
		// 返回的是遍历器对象的内部值。
		
		
	</script>
</body>
</html>